server:
  port: 8086

spring:
  data:
    mongodb:
      port: 27017
      host: localhost
      database: FuelApp

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: allocation-service
    consumer:
      bootstrap-servers: localhost:9092
      group-id: allocation-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      client-id: allocation-service
      enable-auto-commit: false